name: AWS Cleanup

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Destroy Terraform Resources
        run: terraform destroy -auto-approve
        working-directory: terraform

      - name: Delete S3 bucket
        run: |
          aws s3 rm s3://my-sanskrit-survey-frontend-bucket --recursive || true
          aws s3api delete-bucket --bucket my-sanskrit-survey-frontend-bucket || true

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Disable CloudFront Distribution
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='SurveyFrontendCDN'].Id" --output text)
          echo "Disabling CloudFront Distribution: $DISTRIBUTION_ID"
          aws cloudfront get-distribution-config --id $DISTRIBUTION_ID > config.json
          ETag=$(jq -r '.ETag' config.json)
          jq '.DistributionConfig.Enabled = false' config.json > updated-config.json
          aws cloudfront update-distribution \
            --id $DISTRIBUTION_ID \
            --if-match $ETag \
            --distribution-config file://updated-config.json

      - name: Wait for CloudFront Distribution to Disable
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='SurveyFrontendCDN'].Id" --output text)
          echo "Waiting for distribution $DISTRIBUTION_ID to be Disabled..."
          while [[ "$(aws cloudfront get-distribution --id $DISTRIBUTION_ID --query 'Distribution.Status' --output text)" != "Deployed" ]] ||
                [[ "$(aws cloudfront get-distribution --id $DISTRIBUTION_ID --query 'Distribution.DistributionConfig.Enabled' --output text)" == "true" ]]; do
            echo "Still deploying or not yet disabled... waiting 30s"
            sleep 30
          done
          echo "CloudFront distribution is disabled and ready to delete."

      - name: Delete CloudFront Distribution
        run: |
          DISTRIBUTION_ID=$(aws cloudfront list-distributions --query "DistributionList.Items[?Comment=='SurveyFrontendCDN'].Id" --output text)
          echo "Deleting CloudFront Distribution: $DISTRIBUTION_ID"
          aws cloudfront get-distribution-config --id $DISTRIBUTION_ID > config.json
          ETag=$(jq -r '.ETag' config.json)
          aws cloudfront delete-distribution \
            --id $DISTRIBUTION_ID \
            --if-match $ETag
