name: 🔁 Cypress End-to-End Tests

on:
  push:
    branches: 404-Not-Found-Deployment-Testing
  pull_request:
    branches: 404-Not-Found-Deployment Testing

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v3

      - name: 🧪 Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🔨 Build app (optional, if required)
        run: npm run build || echo "No build script"

      - name: 🧫 Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: frontend
          config-file: cypress.config.js
