name: Setup # Deploy React App to S3 + CloudFront

on:
  push:
    branches:
       - 404-Not-Found-Deployment-Testing
  workflow_dispatch:

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init
      working-directory: terraform/frontend-s3

    - name: Empty S3 bucket before destroy
      run: |
        BUCKET_NAME="my-sanskrit-survey-frontend-bucket"
        aws s3 rm s3://$BUCKET_NAME --recursive

    - name: Terraform Destroy
      run: terraform destroy -auto-approve
      working-directory: terraform/frontend-s3
